# Solution to day 25 of AOC 2015, Let It Snow
# https://adventofcode.com/2015/day/25

seed = 20151125                             # "The first code is 20151125."

x, y = 1, 1
while True:
    if x == 3075 and y == 2981:             # "Enter the code at row 2981, column 3075."
        print(seed)
        break

    # "After that, each code is generated by taking the previous one, multiplying it by 252533,
    # and then keeping the remainder from dividing that value by 33554393."
    seed = (seed * 252533) % 33554393

    if y == 1:
        y = x + 1
        x = 1
    else:
        x += 1
        y -= 1
